name: conductor2
description: An app for viewing bus and train times.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.17.0<3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  dio: ^4.0.6
  flutter:
    sdk: flutter
  geolocator: ^8.2.0
  json_annotation: ^4.4.0
  share_plus: ^4.0.4
  shared_preferences: ^2.0.13
  url_launcher: ^6.0.20

dev_dependencies:
  build_runner: ^2.1.8
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  json_serializable: ^6.1.5

flutter:
  uses-material-design: true
